### ISSUE TITLE
PolygonAreaExact seems to give incorrect results

### ISSUE THREAD

**Issue by smirkingman** [noelex/GeographicLib.NET#29] opened 2024-02-15 11:09 UTC
**Describe the bug**
When given a 1-kilometre square of 4 coordinates, PolygonAreaExact returns an area of 2500 square metres

**To Reproduce**

Create a New PolygonAreaExact(GeodesicExact.WGS84)

Add these points, they are anti-clockwise:
46.227634	7.9019728
46.21863761	7.9019728
46.21863761	7.914933282
46.227634	7.914933282

**Expected behavior**
Compute(false,false) = The perimeter is correct: 3999.836689, but the area: 2509.03215 is incorrect, it should be 1'000'000

**Screenshots**
The points displayed with GoogleMaps (the top-left corner is the pitch of the Ottmar Hitzfeld Stadium in Zermatt):
![image](https://github.com/noelex/GeographicLib.NET/assets/22235329/b0b448dd-6abd-437f-a7c3-04c14674d8e0)

**Environment**
Windows 10
Visual Studio 2022 
.Net Framework 4.7.2
GeographicLib 2.1.2

**Comment by noelex** [comment] 2024-02-20 07:07
Thanks for the bug report. The issue is resolved by https://github.com/noelex/GeographicLib.NET/commit/c3bc3a0f84906270314a7132987bcd8e1c7b81c2.

**Closed by noelex** 2024-02-20 07:07 UTC
