### ISSUE TITLE
EGM96-5 Geoid Calculation Error

### ISSUE THREAD

**Issue by jorgeavlobo** [noelex/GeographicLib.NET#27] opened 2022-09-01 15:55 UTC
**Describe the bug**
When trying to calculate the Geoid on a EGM96-5, I get the following error: GeographicLib.GeographicException: 'Error reading scale (...)"

**To Reproduce**
double latitude = 1;
double longitude = 2;
Geoid egm96 = new Geoid("egm96-5", "D:\\Users\\Test\\Documents\\", true, false);
newSensorData.GeoidEGM96 = egm96.Evaluate(latitude, longitude);

**Expected behavior**
A double output.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 104

**Additional context**
The egm96-5.pgm file is in the "D:\\Users\\Test\\Documents\\" folder.

**Comment by noelex** [comment] 2022-09-04 09:15
I was unable to reproduce the issue with EGM96-5 model downloaded from [here](https://sourceforge.net/projects/geographiclib/files/geoids-distrib/).

Could you please attach your `egm96-5.pgm` file?
Or you can enable source link and set a break point at [this line](https://github.com/noelex/GeographicLib.NET/blob/master/GeographicLib/Geoid.cs#L279) to check that whether the value of `Scale` field is a valid floating point number.

**Comment by jorgeavlobo** [comment] 2022-09-05 01:47
@noelex, first of all... Thank you for the reply and for helping me out.
The pgm file I was using was the official one, anyway I downloaded it again from the link you provided and I have the same problem. File in attachment...
When debugging at line 279, I notice that "match" is null.
_'match.Groups' threw an exception of type 'System.NullReferenceException'_
- Line 238 sr is null.
- In line 233 I get the following error: 
![image](https://user-images.githubusercontent.com/12179834/188344298-42216e6c-6fa8-41fb-bf5e-b4c253007b99.png)

Can I share my code with you?

[egm96-5.zip](https://github.com/noelex/GeographicLib.NET/files/9485958/egm96-5.zip)

**Comment by jorgeavlobo** [comment] 2022-09-05 02:14
Apparently It cannot read the file because of the Path construction of the location of the pgm file.
So that you can test it, try saving the pgm file locally on **Temp\egm95-5.pgm**
(with a relative folder path)
How will you write the following code?
_Geoid egm96 = new Geoid("egm96-5", @"Temp", true, false);_
I have tried also with an absolute file path to **C;\Test\Temp\egm95-5.pgm**
But I have been unsuccessful also...

**Comment by noelex** [comment] 2022-09-05 07:25
Thanks for the additional context. I've tried several ways to construct Geoid but was still unable to reproduce.

I don't think this a problem related to the file path as the error you mentioned in OP (`Error reading scale`), will occur only when the file is accessible and contains a line starts with `# Scale`.

It would be helpful if you can provide a minimum project to reproduce the problem.

**Comment by jorgeavlobo** [comment] 2022-09-05 09:43
Once again, thank you for the reply.
As soon as I get home I will build a new solution, replicate the problem, and share the solution with you.
Did you see the image I sent above?
It mentions a file read timeout.

**Comment by noelex** [comment] 2022-09-05 11:51
You're seeing the `InvalidOperationException` because `FileStream` does not support `ReadTimeout` and `WriteTimeout`, which is irrelevant to the problem you are experiencing.

**Comment by jorgeavlobo** [comment] 2022-09-05 13:24
Could you please check the following code please?
Thank you very much.
[https://github.com/jorgeavlobo/GeoidCalculationTest](url)

**Comment by noelex** [comment] 2022-09-05 15:23
Hmm, that's weird. I can run your code without any issue:
![image](https://user-images.githubusercontent.com/15687718/188476082-b109cb83-eb27-4e74-b8ff-85b3622b5317.png)
There isn't much can be done on my side if I can't reproduce the problem.
Could you please verify that:

1. You received a `GeographicException` thrown from [this line](https://github.com/noelex/GeographicLib.NET/blob/v2.0.0/GeographicLib/Geoid.cs#L281).
2. When your application is paused on [this line](https://github.com/noelex/GeographicLib.NET/blob/v2.0.0/GeographicLib/Geoid.cs#L279), what's the value of `match.Groups[2].Value` property.

**Comment by jorgeavlobo** [comment] 2022-09-05 15:55
1 - Yes

![image](https://user-images.githubusercontent.com/12179834/188485258-b8224d8a-8c0e-4e4c-97c9-68602883860a.png)

![image](https://user-images.githubusercontent.com/12179834/188485082-0a512331-c0d9-4c3c-9617-44f3729127fb.png)

2 - No value
**'match.Groups[2].Value' threw an exception of type 'System.NullReferenceException'**

**Comment by jorgeavlobo** [comment] 2022-09-05 16:01
On the test program I provided you I am now having this issue:
![image](https://user-images.githubusercontent.com/12179834/188485981-aed7986f-2cac-47b0-a948-d5fec7496ed4.png)

The previous errors on my previous post were from my original program, not the test one. The test is giving me a different one that you can see on the picture above.

**Comment by noelex** [comment] 2022-09-05 16:13
Well, `match` is `null` because you're debugging a release build and the variable is optimized out.
You can set a break point on [this line](https://github.com/noelex/GeographicLib.NET/blob/v2.0.0/GeographicLib/Geoid.cs#L277) instead and inspect `match` when `key` is `Scale`.

**Comment by noelex** [comment] 2022-09-05 16:16
Also, can you confirm the following code runs in your C# Interactive window?
```
#reset core
double.Parse("0.003")
```

**Comment by jorgeavlobo** [comment] 2022-09-05 16:23
![image](https://user-images.githubusercontent.com/12179834/188488673-e5c178b7-a47d-4e70-b7f9-dc53957bde4a.png)

double.Parse("0.003") does not run on my machine, I always use:
double.Parse(longitudeDegreesString, CultureInfo.InvariantCulture);

**Comment by jorgeavlobo** [comment] 2022-09-05 16:34
![image](https://user-images.githubusercontent.com/12179834/188490051-2939f810-3c8b-4b8b-a235-fa0000988a43.png)

**Comment by noelex** [comment] 2022-09-05 16:35
OK, I think I know the cause of the problem now. I can ship the fix in next preview release.
For now, you can work this around by setting `CultureInfo.CurrentCulture` to `InvariantCulture` on the thread which you construct Geoid.

**Comment by jorgeavlobo** [comment] 2022-09-05 18:25
CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
![image](https://user-images.githubusercontent.com/12179834/188500175-564d2ffc-89fb-474a-9dd6-cddb5e13694f.png)

**Comment by noelex** [comment] 2022-09-06 06:42
Closing as fixed in [2.1.1-preview.2](https://www.nuget.org/packages/GeographicLib.NET/2.1.1-preview.2).
Feel free to reopen this issue if you're still encountering problems after upating the package.

**Closed by noelex** 2022-09-06 06:42 UTC
